rosbag_filepath: "/home/victor/data/building_sim/terrain_coverage_2019-01-21-23-26-31.bag"
skip_first_n_sec: 50
map_evaluation:
  ground_truth_tsdf_layer_filepath: "/home/victor/data/voxgraph/ground_truth_maps/burning_building_rubble"
registration_methods: ["explicit_to_implicit"]
sampling_ratios: [-1.0, 1.0, 0.9, 0.8, 0.7, 0.6, 0.5,  0.4, 0.3, 0.2, 0.1,
                   0.09, 0.08, 0.07, 0.06, 0.05, 0.04, 0.03, 0.02, 0.01, 0.0]
